Library CI files for dp-kafka
ONSdigital/dp-kafka pull request #27
Opened 2021-02-16 20:38 UTC by outsidecoder

### What
Part of a selection of PR to add CI folder for Library, that is <repo>/ci 

### How to review
Add a PR for the repo and Concourse will go through build, test, and audit for this repo.

### Who can review
Anyone with Concourse knowledge.

2021-02-17 07:27 UTC, gedge submitted a review, later dismissed

2021-05-12 08:43 UTC, eldeal approved these changes

2021-05-12 15:20 UTC, nshumoogum requested changes
It's also worth removing `.travis.yml` file as tests run in ci instead of travis

2021-05-12 15:20 UTC, nshumoogum commented on Makefile
> +	go list -json -m all | nancy sleuth --exclude-vulnerability-file ./.nancy-ignore
No need to add the exclude vulnerability flag, it defaults to security codes of `.nancy-ignore`

2021-05-13 07:44 UTC, nshumoogum approved these changes

2021-05-13 08:27 UTC, merged