Update log.go requirement to v2 in go.mod and imports.
ONSdigital/dp-kafka pull request #34
Opened 2021-07-27 16:40 UTC by thomasridd

### What
Update logging statements to format that can be parsed by
elastisearch, e.g.

log.Event(ctx, string, log.FATAL, log.Error(something1), something2)
-> log.Fatal(ctx, string, something1, something2)
log.Event(ctx, string, log.ERROR log.Error(something1), something2)
-> log.Error(ctx, string, something1, something2)
log.Event(ctx, string, log.INFO, log.Error(something))
-> log.Info(ctx, string, log.FormatErrors([]error{something}))
log.Event(ctx, string, log.WARN, log.Error(something))
-> log.Warn(ctx, string, log.FormatErrors([]error{something}))

These changes needed to allow error logs to be properly viewed in
kibana.

### How to review

Run make test
Inspect for obvious errors

### Who can review

Anyone

2021-07-27 18:42 UTC, VivianAllen commented on Makefile
> +	exit
should this run `go fmt`? (see here - https://github.com/ONSdigital/dp-mongodb/blob/main/Makefile). Its inconsistent in other repos though...

2021-07-27 18:43 UTC, VivianAllen commented on admin.go
> -		log.Event(nil, "creating ACL", log.Data{"res": acl.Resource, "acl": acl.Acl})
mybe worth a single call to context.Background() there, that can be reused on l40?

2021-07-27 18:46 UTC, VivianAllen commented on ci/lint.yml
> +    tag: 1.15.7
I think 'latest' goland version here is what @nshumoogum recommended when we're adding new ones of these (a lot of the olds ymls are still old versions - there'll be another bit of work to fix that)

2021-07-27 18:57 UTC, VivianAllen requested changes
few tweaks I think and this is ready to go

2021-07-27 19:00 UTC, VivianAllen commented on ci/lint.yml
> +    tag: 1.15.7
NB - think I messed up the 'request changes' bit on me review - refers to this comment (everything else suggested / for discussion)

2021-07-28 07:35 UTC, VivianAllen commented on ci/lint.yml
> +  path: dp-kafka/ci/scripts/lint.sh
looks like `lint.sh` might be missing

2021-07-28 12:24 UTC, VivianAllen commented on Makefile
> +	exit
following discussion with @nshumoogum this should be left as a noop

2021-07-28 15:19 UTC, thomasridd commented on Makefile
> +	exit
as I understand no

2021-07-29 14:31 UTC, thomasridd commented on ci/lint.yml
> +  path: dp-kafka/ci/scripts/lint.sh
fixed that one

2021-07-29 14:40 UTC, thomasridd commented on admin.go
> -		log.Event(nil, "creating ACL", log.Data{"res": acl.Resource, "acl": acl.Acl})
unless it is a serious performance hit I'd consider it more readable having logging as a single line - depends - is there a codebase convention?

2021-07-29 14:41 UTC, thomasridd commented on ci/lint.yml
> +    tag: 1.15.7
done that

2021-07-30 09:11 UTC, VivianAllen commented on admin.go
> -		log.Event(nil, "creating ACL", log.Data{"res": acl.Resource, "acl": acl.Acl})
Sorry, I haven't made myself clear - I mean having ctx := context.Background() somewhere outside of the log statements, and then use the ctx variable both here and on l40? Not exactly a major issue either way

2021-07-30 09:19 UTC, VivianAllen approved these changes
ready to go I think

2021-07-30 10:36 UTC, merged