Fix context usage and add Channels for state changes
ONSdigital/dp-kafka pull request #42
Opened 2021-10-28 11:25 UTC by DavidSubiros

### What

This PR corresponds to a conversation with @redhug1 (context) and also the experience of using `dp-kafka` in component tests (need to wait until consumer is in `Consuming` state)

Fix usage of context:
- Create a new child context on message/batch handlers, which is cancelled as soon as the caller returns
- Close consumer/producer when a context.Done() is received
- Fixed bug with `waitWithTimeout` for expired contexts
- Added unit tests

Created channels for State transitions
- For each state transition, the consumer-group state machine closes the new state channel and opens a new channel for the old state.
- This means that a caller can block execution until a particular state is reached, like so (e.g. `Consuming` state):
```
<-consumer.Channels().State.Consuming
```

Update:
Extended PR to cover:
- Safe channel close/send and check ok on recieved values
- GetRetryPeriod now restarts the backoff algorithm after reaching the max period, and the values are configurable.

### How to review

- Make sure code changes make sense
- Make sure new unit tests make sense and cover new functionality
- Make sure unit tests pass
(info only): usage example: https://github.com/ONSdigital/dp-cantabular-csv-exporter/pull/36

### Who can review

anyone

2021-11-01 08:58 UTC, redhug1 commented on consumer_group.go
> +	if ctx == nil {
The comment on line 307 needs removing

2021-11-01 09:07 UTC, redhug1 commented on producer.go
>  			fmt.Errorf("timed out while waiting for all loops to finish: %w", ctx.Err()),
is the comment on line 220 correct (which is):
// If the closer channel is closed, it closes the closed channel straight away and stops.

2021-11-01 09:15 UTC, redhug1 commented on consumer_group.go
> +	didTimeout := WaitWithTimeout(cg.wgClose)
line 385 has :
initAttempt++

I think that once it gets to a value greater then 5 it should be reset to a value of 1

2021-11-01 09:29 UTC, redhug1 commented on consumer_group.go
> +
Does the go routing in 'createConsumeLoop()' need a:

case <-ctx.Done():

??
(i don't think it would harm ?)

2021-11-01 10:08 UTC, redhug1 requested changes
I've added a number of things to attend to and consider ...

2021-11-01 10:31 UTC, DavidSubiros commented on producer.go
> +	didTimeout := WaitWithTimeout(p.wgClose)
amended, and also added the `retry` description.

2021-11-01 10:31 UTC, DavidSubiros commented on consumer_group.go
> +	didTimeout := WaitWithTimeout(cg.wgClose)
It makes sense, so that we don't have things waiting for ridicolous ammounts of time. But maybe it makes more sense that `WaitWithTimeout` can calculate the exponential time based on `attempts % 5` instead of attempts (so that callers don't need to worry about this, and logs have the right number of attempts value.)

2021-11-01 10:31 UTC, DavidSubiros commented on producer.go
> +	didTimeout := WaitWithTimeout(p.wgClose)
amended, and also added the retry description.

2021-11-01 10:38 UTC, DavidSubiros commented on consumer_group.go
> +	didTimeout := WaitWithTimeout(cg.wgClose)
In fact, there is already a max vaule of 31 sec `var MaxRetryInterval = 31 * time.Second` - what I can do is set the module according to that value, so that we will "restart" the algorithm every time that the maxRetryInterval would have been reached.
e.g. sleep periods:
attempt 1: 1 sec
attempt 2: 2 sec
attempt 3: 4 sec
attempt 4: 8 sec
attempt 5: 16 sec
attempt 6: 1 sec
attempt 7: 2 sec
attempt 8: 4 sec
...

2021-11-01 12:16 UTC, redhug1 commented on consumer_group.go
> +	didTimeout := WaitWithTimeout(cg.wgClose)
Yes, ok, as long as we have some sort of sensible limit.

2021-11-01 12:22 UTC, DavidSubiros commented on consumer_group.go
> +
I started by adding `ctx.Done()` to all the loops in `dp-kafka`, but then I decided that it would make more sense to just create an extra go-routine when we create a consumer / producer, which would trigger a close when we recieve a context.Done(), so that all go-routines can finish on closer channel being closed (the same that happens now), and the code could be cleaner, with less duplication.

2021-11-01 12:23 UTC, DavidSubiros commented on consumer_group.go
> +	didTimeout := WaitWithTimeout(cg.wgClose)
Update: added this logic (will be committed shortly - I will also add some comments where we call `GetRetryTime` to make sure the caller doesn't need to worry about this.)

2021-11-01 12:25 UTC, redhug1 commented on consumer_group.go
> +
OK

2021-11-01 12:31 UTC, DavidSubiros commented on consumer_handler.go
> +				log.Info(ctx, "batch is full - processing batch", log.Data{"batchsize": batch.Size()})
It could potentially, especially in tasks like draining topics. I think it makes sense to remove this log (which would make the code consistent with single message handling).

2021-11-01 12:33 UTC, DavidSubiros commented on consumer_handler.go
> +			return
I started adding it but then created a 'context.Done' handling go-routine instead:
https://github.com/ONSdigital/dp-kafka/pull/42#discussion_r740170467

2021-11-01 12:42 UTC, DavidSubiros commented on producer.go
> +		return errors.New("nil context was passed to producer close")
I will double-check all channels. If we call 'Close' on a closed producer/consumer, it shuld jsut return, so the channels wouldn't be closed again, but it doesn't hurt having 'saveClose' / 'saveSend', etc.

2021-11-02 10:33 UTC, redhug1 approved these changes

2021-11-02 10:38 UTC, merged