WIP: Add linter and fix lint issues
ONSdigital/dp-kafka pull request #65
Opened 2022-08-18 20:24 UTC by rahulPalliyalil

### What

Describe what you have changed and why.

### How to review

Describe the steps required to test the changes.

### Who can review

Describe who worked on the changes, so that other people can review.

2022-09-12 15:51 UTC, nshumoogum requested changes

2022-09-12 15:51 UTC, nshumoogum commented on config_security.go
> +	"os"
Do we not use io instead of io/ioutil? Just for consistency instead of using os?

2022-09-12 15:51 UTC, nshumoogum commented on global.go
> -	"math/rand"
Why switching out `math/rand` with `crypto/rand` ?

2022-09-12 15:54 UTC, rahulPalliyalil commented on global.go
> -	"math/rand"
use of crypto rand is suggested by the gosec linter as math rand is considered weaker random number generator.

2022-09-12 15:54 UTC, rahulPalliyalil commented on config_security.go
> +	"os"
ioutil package is depreciated  after 1.18, so that's why used os instead of ioutil.

2022-09-12 16:03 UTC, nshumoogum submitted a review, later dismissed

2022-12-01 17:12 UTC, nshumoogum approved these changes

2022-12-01 17:51 UTC, merged